/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'on-surface': '#191b23',
        'surface-tint': '#0053db',
        'on-primary-fixed': '#00174b',
        error: '#ba1a1a',
        background: '#faf8ff',
        'secondary-fixed': '#d3e4fe',
        'on-secondary-container': '#54647a',
        'on-secondary-fixed-variant': '#38485d',
        secondary: '#505f76',
        'inverse-on-surface': '#f0f0fb',
        outline: '#737686',
        'on-error': '#ffffff',
        'tertiary-fixed': '#ffdbcd',
        'surface-container-highest': '#e1e2ed',
        'on-primary-container': '#eeefff',
        'primary-fixed': '#dbe1ff',
        'tertiary-container': '#bc4800',
        'on-primary-fixed-variant': '#003ea8',
        'surface-dim': '#d9d9e5',
        'secondary-container': '#d0e1fb',
        'on-tertiary-fixed': '#360f00',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#7d2d00',
        'inverse-surface': '#2e3039',
        'surface-variant': '#e1e2ed',
        'on-tertiary-container': '#ffede6',
        'on-surface-variant': '#434655',
        'inverse-primary': '#b4c5ff',
        'primary-container': '#2563eb',
        'surface-container-low': '#f3f3fe',
        'surface-bright': '#faf8ff',
        tertiary: '#943700',
        'tertiary-fixed-dim': '#ffb596',
        'on-primary': '#ffffff',
        primary: '#004ac6',
        'surface-container-high': '#e7e7f3',
        'on-background': '#191b23',
        surface: '#faf8ff',
        'outline-variant': '#c3c6d7',
        'on-error-container': '#93000a',
        'surface-container': '#ededf9',
        'primary-fixed-dim': '#b4c5ff',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary-fixed': '#0b1c30',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        'container-max': '1200px',
      },
      fontFamily: {
        'headline-md': ['Manrope'],
        'headline-lg': ['Manrope'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'display-lg': ['Manrope'],
        'body-sm': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': [
          '14px',
          {
            lineHeight: '20px',
            letterSpacing: '0.01em',
            fontWeight: '500',
          },
        ],
        'display-lg': [
          '48px',
          {
            lineHeight: '56px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('tailwindcss/plugin')(({ addBase }) => {
    addBase({
      '*': {
        'scrollbar-width': 'thin',
        'scrollbar-color': '#d9d9e5 transparent',
      },
    });
  })],
};
